# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a86b13dc31837e622993d5bb4cb7a105dc3e3cae26eeb1f7b19716fa43e8ac1b8086df84068ed9581f0caeaf09e0cf6657bb7f18996bc423b4a357d7104adea

test:
  secret_key_base: 716da960bdfd1909aa42ceeeec426f0d75a0aa0f7745a4c6afc36691407e3f71690f9a50ef4aa31d3c043b5d40eabbfa4b15855b386f4fa4b754a3ad4872de38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
